sudo: required
language: python
services: docker

env:
  IMAGE=antocuni/pypy-wheels
  TAG=`docker/get_tag.sh`

before_install:
  - openssl aes-256-cbc -K $encrypted_9edd802e88c8_key -iv $encrypted_9edd802e88c8_iv -in ./travis/travis.rsa.enc -out ./travis/travis.rsa -d

install:
  - ./docker/build_image.sh

script:
  - echo $TAG
  - # ./clone-gh-pages.sh
  - # ./build.sh
  - #./commit-gh-pages.sh
